import { v } from "convex/values";
import { mutation, query, QueryCtx, MutationCtx } from "./_generated/server";
import { requireAdvisor } from "./activityLogs";
import { Id } from "./_generated/dataModel";

type BuyerAccessStatus = "hidden" | "teaser_shared" | "nda_required" | "intro_approved" | "introduced";

const ACCESS_TRANSITIONS: Record<BuyerAccessStatus, readonly BuyerAccessStatus[]> = {
  hidden: ["hidden", "teaser_shared"],
  teaser_shared: ["hidden", "teaser_shared", "nda_required"],
  nda_required: ["hidden", "nda_required", "intro_approved"],
  intro_approved: ["hidden", "intro_approved", "introduced"],
  introduced: ["hidden", "introduced"],
};

export function assertAccessTransition(from: BuyerAccessStatus, to: BuyerAccessStatus): void {
  if (!ACCESS_TRANSITIONS[from].includes(to)) throw new Error(`Invalid buyer access transition: ${from} → ${to}`);
}

// List all matches
export const list = query({
  args: {},
  handler: async (ctx: QueryCtx) => {
    await requireAdvisor(ctx);
    return await ctx.db.query("matches").order("desc").collect();
  },
});

// List all matches populated with buyer and seller details (database join)
export const listPopulated = query({
  args: {},
  handler: async (ctx: QueryCtx) => {
    await requireAdvisor(ctx);
    const matches = await ctx.db.query("matches").order("desc").collect();

    // Populate relational details in a single pass
    const populated = await Promise.all(
      matches.map(async (m) => {
        const buyer = await ctx.db.get(m.buyerId);
        const seller = await ctx.db.get(m.sellerId);
        return {
          ...m,
          buyerName: buyer?.name || "Unknown Buyer",
          buyerEmail: buyer?.email || "",
          sellerBusinessName: seller?.businessName || "Unknown Seller",
          sellerSector: seller?.sector || "",
          sellerRevenueRange: seller?.revenueRange || "under_500k",
        };
      })
    );

    return populated;
  },
});

// List matches for a specific seller mandate
export const listBySeller = query({
  args: { sellerId: v.id("sellers") },
  handler: async (ctx: QueryCtx, args) => {
    await requireAdvisor(ctx);
    return await ctx.db
      .query("matches")
      .withIndex("by_seller", (q) => q.eq("sellerId", args.sellerId))
      .collect();
  },
});

// Get a single match by ID
export const get = query({
  args: { id: v.id("matches") },
  handler: async (ctx: QueryCtx, args) => {
    await requireAdvisor(ctx);
    return await ctx.db.get(args.id);
  },
});

// Upsert a match generated by the Claude matching agent
export const upsertFromAI = mutation({
  args: {
    sellerId: v.id("sellers"),
    buyerId: v.id("buyers"),
    aiScore: v.number(),
    aiReasoning: v.string(),
    aiMatchedCriteria: v.array(v.string()),
  },
  handler: async (
    ctx: MutationCtx,
    args: {
      sellerId: Id<"sellers">;
      buyerId: Id<"buyers">;
      aiScore: number;
      aiReasoning: string;
      aiMatchedCriteria: string[];
    }
  ) => {
    await requireAdvisor(ctx);
    const { sellerId, buyerId, aiScore, aiReasoning, aiMatchedCriteria } = args;
    const now = Date.now();

    // Check if there is an existing match record between the buyer and seller
    const existing = await ctx.db
      .query("matches")
      .withIndex("by_seller", (q) => q.eq("sellerId", sellerId))
      .filter((q) => q.eq(q.field("buyerId"), buyerId))
      .unique();

    if (existing) {
      // Update the AI recommendation parameters of the existing match
      await ctx.db.patch(existing._id, {
        aiScore,
        aiReasoning,
        aiMatchedCriteria,
        updatedAt: now,
      });
      return existing._id;
    } else {
      // Create a brand new match, starting at the "suggested" pipeline stage
      const id = await ctx.db.insert("matches", {
        sellerId,
        buyerId,
        aiScore,
        aiReasoning,
        aiMatchedCriteria,
        status: "suggested",
        buyerAccessStatus: "hidden",
        createdAt: now,
        updatedAt: now,
      });
      return id;
    }
  },
});

// Log match generation completed event in activityLogs
export const logMatchGeneration = mutation({
  args: {
    sellerId: v.id("sellers"),
    matchCount: v.number(),
  },
  handler: async (
    ctx: MutationCtx,
    args: {
      sellerId: Id<"sellers">;
      matchCount: number;
    }
  ) => {
    await requireAdvisor(ctx);
    const seller = await ctx.db.get(args.sellerId);
    if (!seller) throw new Error("Seller mandate not found");

    const now = Date.now();
    await ctx.db.insert("activityLogs", {
      action: "match_generated",
      entityType: "seller",
      entityId: args.sellerId,
      entityLabel: "Seller profile",
      details: `${args.matchCount} AI match recommendations generated`,
      createdAt: now,
    });
  },
});

// Get a single match by ID, fully populated with buyer and seller details
export const getPopulated = query({
  args: { id: v.id("matches") },
  handler: async (ctx: QueryCtx, args) => {
    await requireAdvisor(ctx);
    const match = await ctx.db.get(args.id);
    if (!match) return null;

    const buyer = await ctx.db.get(match.buyerId);
    const seller = await ctx.db.get(match.sellerId);

    return {
      ...match,
      buyerName: buyer?.name || "Unknown Buyer",
      buyerEmail: buyer?.email || "",
      buyerPhone: buyer?.phone || "",
      buyerSectorInterest: buyer?.sectorInterest || [],
      buyerBudgetMin: buyer?.budgetMin ?? 0,
      buyerBudgetMax: buyer?.budgetMax ?? 0,
      buyerGeography: buyer?.geography || [],
      buyerFinancingType: buyer?.financingType || "unknown",
      buyerAcquisitionExperience: buyer?.acquisitionExperience || "first_time",
      buyerAcquisitionTimeline: buyer?.acquisitionTimeline || "24mo_plus",
      buyerNdaSigned: buyer?.ndaSigned ?? false,
      buyerProofOfFundsReviewed: buyer?.proofOfFundsReviewed ?? false,
      buyerBackgroundCheckComplete: buyer?.backgroundCheckComplete ?? false,
      buyerNotes: buyer?.notes || "",
      
      sellerBusinessName: seller?.businessName || "Unknown Seller",
      sellerName: seller?.name || "",
      sellerEmail: seller?.email || "",
      sellerPhone: seller?.phone || "",
      sellerSector: seller?.sector || "",
      sellerGeography: seller?.geography || "",
      sellerRevenueRange: seller?.revenueRange || "under_500k",
      sellerEbitdaRange: seller?.ebitdaRange || "under_100k",
      sellerEmployeeCount: seller?.employeeCount || "1_5",
      sellerYearsInOperation: seller?.yearsInOperation ?? 0,
      sellerTransactionType: seller?.transactionType || "full_sale",
      sellerReasonForSale: seller?.reasonForSale || "",
      sellerReadinessScore: seller?.readinessScore ?? 0,
      sellerNotes: seller?.notes || "",
    };
  },
});

// Update match pipeline status, advisor notes, and/or buyer access visibility
export const updateStatus = mutation({
  args: {
    id: v.id("matches"),
    status: v.union(
      v.literal("suggested"),
      v.literal("reviewed"),
      v.literal("approved"),
      v.literal("introduced"),
      v.literal("nda_signed"),
      v.literal("in_discussions"),
      v.literal("closed_won"),
      v.literal("closed_lost"),
      v.literal("rejected")
    ),
    advisorNotes: v.optional(v.string()),
    buyerAccessStatus: v.optional(
      v.union(
        v.literal("hidden"),
        v.literal("teaser_shared"),
        v.literal("nda_required"),
        v.literal("intro_approved"),
        v.literal("introduced")
      )
    ),
    dealValue: v.optional(v.number()),
    targetCloseDate: v.optional(v.number()),
  },
  handler: async (
    ctx: MutationCtx,
    args: {
      id: Id<"matches">;
      status:
        | "suggested"
        | "reviewed"
        | "approved"
        | "introduced"
        | "nda_signed"
        | "in_discussions"
        | "closed_won"
        | "closed_lost"
        | "rejected";
      advisorNotes?: string;
      buyerAccessStatus?: "hidden" | "teaser_shared" | "nda_required" | "intro_approved" | "introduced";
      dealValue?: number;
      targetCloseDate?: number;
    }
  ) => {
    const { identity, user } = await requireAdvisor(ctx);
    const existing = await ctx.db.get(args.id);
    if (!existing) throw new Error("Match recommendation not found");
    const currentAccess = existing.buyerAccessStatus ?? "hidden";
    const nextAccess = args.buyerAccessStatus ?? currentAccess;
    assertAccessTransition(currentAccess, nextAccess);
    if (nextAccess === "intro_approved" || nextAccess === "introduced") {
      const buyerForAccess = await ctx.db.get(existing.buyerId);
      if (!buyerForAccess || buyerForAccess.qualificationStatus !== "qualified" || !buyerForAccess.ndaSigned) {
        throw new Error("Qualified buyer with verified NDA is required for this access level");
      }
    }

    const oldStatus = existing.status;
    const now = Date.now();

    await ctx.db.patch(args.id, {
      status: args.status,
      advisorNotes: args.advisorNotes !== undefined ? args.advisorNotes : existing.advisorNotes,
      buyerAccessStatus: nextAccess,
      dealValue: args.dealValue !== undefined ? args.dealValue : existing.dealValue,
      targetCloseDate: args.targetCloseDate !== undefined ? args.targetCloseDate : existing.targetCloseDate,
      updatedAt: now,
    });

    // Log the event based on transition
    let action = "match_stage_advanced";
    if (args.status === "approved") {
      action = "match_approved";
    } else if (args.status === "rejected") {
      action = "match_rejected";
    }

    await ctx.db.insert("activityLogs", {
      action,
      entityType: "match",
      entityId: args.id,
      entityLabel: "Match record",
      details: `${oldStatus} → ${args.status}`,
      actorClerkId: identity.subject,
      actorUserId: user._id,
      actorRole: "admin",
      outcome: "success",
      source: "ui",
      createdAt: now,
    });

    return args.id;
  },
});

// List populated matches for the buyer portal, excluding hidden matches and raw seller contact info
export const listPopulatedForBuyer = query({
  args: {},
  handler: async (ctx: QueryCtx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) return [];

    const user = await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .unique();

    if (!user || user.role !== "buyer") return [];

    const buyer = await ctx.db
      .query("buyers")
      .withIndex("by_user_id", (q) => q.eq("userId", user._id))
      .unique();

    if (!buyer || buyer.qualificationStatus !== "qualified") return [];

    const matches = await ctx.db
      .query("matches")
      .withIndex("by_buyer", (q) => q.eq("buyerId", buyer._id))
      .collect();

    const visibleMatches = matches.filter((match) => {
      if (!match.buyerAccessStatus || match.buyerAccessStatus === "hidden") return false;
      if (
        (match.buyerAccessStatus === "intro_approved" || match.buyerAccessStatus === "introduced") &&
        !buyer.ndaSigned
      ) return false;
      return true;
    });

    const populated = await Promise.all(
      visibleMatches.map(async (m) => {
        const seller = await ctx.db.get(m.sellerId);
        if (!seller) return null;
        const base = {
          sellerBusinessName: m.buyerAccessStatus === "introduced" ? seller.businessName : "Confidential Project",
          sellerSector: seller.sector,
          sellerGeography: seller.geography,
          sellerRevenueRange: seller.revenueRange,
          sellerTransactionType: seller.transactionType,
          requiresNda: m.buyerAccessStatus === "nda_required",
          canContactAdvisor: m.buyerAccessStatus === "intro_approved" || m.buyerAccessStatus === "introduced",
        };
        if (m.buyerAccessStatus === "teaser_shared" || m.buyerAccessStatus === "nda_required") return base;
        return {
          ...base,
          sellerEbitdaRange: seller.ebitdaRange,
          sellerEmployeeCount: seller.employeeCount,
          sellerYearsInOperation: seller.yearsInOperation,
          ...(m.buyerAccessStatus === "introduced" ? { sellerReasonForSale: seller.reasonForSale } : {}),
        };
      })
    );
    return populated.filter((match) => match !== null);
  },
});
