/* eslint-disable */
/**
 * Generated API list.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.39.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as activityLogs from "../activityLogs.js";
import type * as buyers from "../buyers.js";
import type * as sellers from "../sellers.js";
import type * as dashboard from "../dashboard.js";

/**
 * A utility for referencing Convex functions in your app's queries and mutations.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  activityLogs: typeof activityLogs;
  buyers: typeof buyers;
  sellers: typeof sellers;
  dashboard: typeof dashboard;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
