/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.39.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { DocumentByName, TableNamesByName, SystemTableNamesByName } from "convex/server";

export type DataModel = {
  buyers: {
    document: {
      name: string;
      email: string;
      phone?: string;
      sectorInterest: string[];
      budgetMin: number;
      budgetMax: number;
      geography: string[];
      financingType: "cash" | "financed" | "mixed" | "unknown";
      acquisitionExperience: "first_time" | "experienced" | "serial";
      acquisitionTimeline: "0_6mo" | "6_12mo" | "12_24mo" | "24mo_plus";
      proofOfFundsReviewed: boolean;
      ndaSigned: boolean;
      backgroundCheckComplete: boolean;
      qualificationStatus: "pending" | "qualified" | "disqualified";
      notes?: string;
      createdAt: number;
      updatedAt: number;
      _id: Id<"buyers">;
      _creationTime: number;
    };
    insert: any;
    patch: any;
    indexes: never;
  };
  sellers: any;
  matches: any;
  activityLogs: {
    document: {
      action: string;
      entityType: "buyer" | "seller" | "match";
      entityId: string;
      entityLabel: string;
      details?: string;
      createdAt: number;
      _id: Id<"activityLogs">;
      _creationTime: number;
    };
    insert: any;
    patch: any;
    indexes: {
      by_created_at: ["createdAt"];
    };
  };
};

export type Document<T extends TableNamesByName<DataModel>> = DocumentByName<
  DataModel,
  T
>;

export type SystemTableNames = SystemTableNamesByName<DataModel>;
export type SystemDocument<T extends SystemTableNames> = any;

export type Id<T extends TableNamesByName<DataModel> | SystemTableNames> = string & {
  __tableName: T;
};
