// lib/copy.ts
// Home for all UI text strings for future French localization support.

export const COPY = {
  app: {
    title: "WAMA Platform",
    subtitle: "Internal Advisor Portal",
    advisor: "Advisor Panel",
    signOut: "Sign Out",
  },
  nav: {
    dashboard: "Dashboard",
    buyers: "Buyers",
    sellers: "Sellers",
    matches: "Matches",
  },
  dashboard: {
    pageTitle: "Dashboard",
    welcome: "Welcome back, William",
    subtitle: "Overview of your deal pipeline, active matches, and system activity.",
    stats: {
      totalBuyers: "Total Buyers",
      totalSellers: "Total Sellers",
      pendingReviews: "Pending Qualification",
      activeMatches: "Active Matches",
    },
    activityFeedTitle: "Recent Advisor Activities",
    noActivity: "No recent activity logged.",
  },
  buyers: {
    pageTitle: "Buyers",
    newButton: "Add Buyer",
    listSubtitle: "Manage and qualify buy-side clients and acquisition criteria.",
    tabs: {
      all: "All",
      pending: "Pending",
      qualified: "Qualified",
      disqualified: "Disqualified",
    },
    statusLabels: {
      pending: "Pending Review",
      qualified: "Qualified",
      disqualified: "Disqualified",
    },
    fields: {
      name: "Buyer Name",
      email: "Email Address",
      phone: "Phone Number",
      budgetMin: "Minimum Budget (CAD)",
      budgetMax: "Maximum Budget (CAD)",
      sectors: "Sectors of Interest",
      geographies: "Preferred Geographies",
      financing: "Financing Type",
      experience: "Acquisition Experience",
      timeline: "Acquisition Timeline",
      notes: "Internal Advisor Notes",
    },
  },
  sellers: {
    pageTitle: "Sellers",
    newButton: "Add Seller",
    listSubtitle: "Manage and qualify sell-side mandates, checklists, and matching.",
    tabs: {
      all: "All",
      pending: "Pending Review",
      qualified: "Qualified Mandates",
      disqualified: "Disqualified",
    },
    readinessChecklist: {
      title: "Document Readiness Checklist",
      financialStatements: "Financial statements available (3 years)",
      taxReturns: "Tax returns available (3 years)",
      leaseDocuments: "Lease/property documents available",
      corporateDocuments: "Corporate registration documents available",
      ndaSigned: "NDA signed and active",
      scoreLabel: "Readiness Score",
    },
    fields: {
      businessName: "Business Name (Internal)",
      ownerName: "Owner Name",
      email: "Contact Email",
      phone: "Contact Phone",
      sector: "Sector / Industry",
      revenueRange: "Revenue Range (CAD)",
      ebitdaRange: "EBITDA Range (CAD)",
      employeeCount: "Employee Count",
      yearsInOperation: "Years in Operation",
      geography: "Business Geography",
      transactionType: "Transaction Type",
      reasonForSale: "Reason for Sale (AI Match Ready Summary)",
      notes: "Internal Advisor Notes",
    },
  },
  matches: {
    pageTitle: "Match Recommendations",
    listSubtitle: "AI-assisted matches between qualified buyers and active mandates.",
    generateButton: "Generate AI Matches",
    generating: "Analyzing Fit & Generating Matches...",
    pipelineStages: {
      suggested: "Suggested",
      reviewed: "Reviewed",
      approved: "Approved",
      introduced: "Introduced",
      nda_signed: "NDA Signed",
      in_discussions: "In Discussions",
      closed_won: "Closed — Won",
      closed_lost: "Closed — Lost",
      rejected: "Rejected",
    },
    details: {
      matchScore: "Match Score",
      fitReasoning: "AI Fit Reasoning",
      matchedCriteria: "Matched Criteria",
      unqualifiedWarning: "Matches can only be generated for active, qualified seller profiles.",
    },
  },
  common: {
    save: "Save Details",
    cancel: "Cancel",
    loading: "Loading...",
    noResults: "No results found.",
    error: "An error occurred.",
  },
} as const;
